#!/usr/bin/env bash
# vertica-adhd installer
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/mertozkarakas/vertica-adhd/main/install.sh | bash
# Or:
#   bash install.sh
#
# Idempotent: safe to re-run. Won't clobber an existing .env.

set -euo pipefail

# ---------- pretty output ----------
if [[ -t 1 ]]; then
  BOLD=$(printf '\033[1m'); DIM=$(printf '\033[2m'); RED=$(printf '\033[31m')
  GREEN=$(printf '\033[32m'); YELLOW=$(printf '\033[33m'); RESET=$(printf '\033[0m')
else
  BOLD=""; DIM=""; RED=""; GREEN=""; YELLOW=""; RESET=""
fi

say() { printf '%s\n' "${BOLD}==>${RESET} $*"; }
warn() { printf '%s\n' "${YELLOW}warn:${RESET} $*" >&2; }
die() { printf '%s\n' "${RED}error:${RESET} $*" >&2; exit 1; }

# ---------- config ----------
IMAGE="${VERTICA_ADHD_IMAGE:-ghcr.io/mertozk/vertica-adhd:latest}"
INSTALL_DIR="${VERTICA_ADHD_DIR:-$HOME/vertica/adhd}"
PORT="${VERTICA_ADHD_PORT:-8088}"

# ---------- pre-flight ----------
say "Checking prerequisites"

if ! command -v docker >/dev/null 2>&1; then
  die "docker not found. Install Docker Engine first: https://docs.docker.com/engine/install/"
fi

if ! docker compose version >/dev/null 2>&1; then
  die "docker compose plugin not found. Install it: https://docs.docker.com/compose/install/linux/"
fi

if ! docker info >/dev/null 2>&1; then
  die "docker daemon not reachable. Is the service running? Try: sudo systemctl start docker"
fi

say "Installing into ${BOLD}${INSTALL_DIR}${RESET}"
mkdir -p "${INSTALL_DIR}/data/brain/daily"

# ---------- compose file ----------
COMPOSE_FILE="${INSTALL_DIR}/docker-compose.yml"
if [[ ! -f "${COMPOSE_FILE}" ]]; then
  say "Writing docker-compose.yml"
  cat > "${COMPOSE_FILE}" <<COMPOSE
services:
  vertica-adhd:
    image: ${IMAGE}
    container_name: vertica-adhd
    restart: unless-stopped
    ports:
      - "${PORT}:8000"
    env_file:
      - .env
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
COMPOSE
else
  say "docker-compose.yml already present — leaving it alone"
fi

# ---------- env ----------
ENV_FILE="${INSTALL_DIR}/.env"
if [[ -f "${ENV_FILE}" ]]; then
  say ".env already present — skipping interactive setup"
else
  say "First-time setup — answer a few questions (press enter to accept defaults)"
  echo

  read_default() {
    # $1=prompt, $2=default; reads from /dev/tty so curl|bash still works
    local prompt="$1" default="$2" reply=""
    if [[ -r /dev/tty ]]; then
      printf "  %s [%s]: " "${prompt}" "${default}" > /dev/tty
      IFS= read -r reply < /dev/tty || reply=""
    fi
    printf '%s' "${reply:-$default}"
  }

  USER_NAME=$(read_default "Your first name" "$(id -un 2>/dev/null || echo friend)")
  USER_TIMEZONE=$(read_default "Timezone (IANA)" "$(cat /etc/timezone 2>/dev/null || echo UTC)")
  ROUTER_URL=$(read_default "Vertica router URL" "http://vertica-router:8080")
  ROUTER_KEY=$(read_default "Vertica router API key" "changeme")
  HA_URL=$(read_default "Home Assistant URL (blank to skip notifications)" "")
  HA_TOKEN=$(read_default "Home Assistant long-lived access token" "")
  HA_TARGET=$(read_default "HA notify target (e.g. mobile_app_my_iphone)" "")
  PUBLIC_URL=$(read_default "Public URL for mobile (Tailscale or LAN)" "http://$(hostname):${PORT}")

  cat > "${ENV_FILE}" <<ENV
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Edit anytime; run: docker compose up -d  to apply.

VERTICA_ROUTER_URL=${ROUTER_URL}
VERTICA_ROUTER_API_KEY=${ROUTER_KEY}
DEFAULT_MODEL=claude-sonnet-4-6

HA_URL=${HA_URL}
HA_TOKEN=${HA_TOKEN}
HA_NOTIFY_TARGET=${HA_TARGET}

PUBLIC_URL=${PUBLIC_URL}

USER_NAME=${USER_NAME}
USER_TIMEZONE=${USER_TIMEZONE}
MORNING_CRON=0 9 * * *
EVENING_CRON=0 21 * * *

DATA_DIR=/data
ENV
  chmod 600 "${ENV_FILE}"
  say "Wrote ${ENV_FILE}"
fi

# ---------- pull + start ----------
say "Pulling image ${IMAGE}"
( cd "${INSTALL_DIR}" && docker compose pull )

say "Starting vertica-adhd"
( cd "${INSTALL_DIR}" && docker compose up -d )

# Wait for healthcheck
say "Waiting for the service to come up"
ATTEMPTS=0
until curl -fsS "http://localhost:${PORT}/healthz" >/dev/null 2>&1; do
  ATTEMPTS=$((ATTEMPTS + 1))
  if (( ATTEMPTS > 30 )); then
    warn "Service didn't respond in 30s. Check logs:"
    warn "  cd ${INSTALL_DIR} && docker compose logs -f"
    exit 1
  fi
  sleep 1
done

echo
echo "${GREEN}Installed.${RESET}"
echo
echo "  Dashboard: ${BOLD}http://$(hostname):${PORT}/${RESET}"
echo "  Mobile:    ${BOLD}http://$(hostname):${PORT}/m/${RESET}"
echo "  Data:      ${DIM}${INSTALL_DIR}/data/${RESET}"
echo "  Config:    ${DIM}${INSTALL_DIR}/.env${RESET}"
echo
echo "Update later with:"
echo "  cd ${INSTALL_DIR} && docker compose pull && docker compose up -d"
echo
echo "Edit coaching behavior live (no restart):"
echo "  ${INSTALL_DIR}/data/brain/COACH.md"
